name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  pypi-test-publish:
    name: Publish to PyPI Test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/project/webcomponentsscan
    permissions:
      id-token: write
    steps:
      - name: Publish package distribution to PyPI test
        uses: pypa/gh-action-pypi-publish@release/v1.11
        with:
          repository-url: https://test.pypi.org/legacy/
